/**
 * AUTO-GENERATED by scripts/gen-migrations.ts — DO NOT EDIT BY HAND.
 *
 * Ordered SQL migrations embedded for RUNTIME application by the setup wizard
 * (see lib/migrate-runtime.ts). Regenerate with: pnpm gen:migrations
 */
/* eslint-disable */
export const SCHEMA_VERSION = "9999b_share_activation";

export interface EmbeddedMigration {
  tag: string;
  /** Individual statements, already split on drizzle's statement-breakpoint. */
  statements: string[];
}

export const MIGRATIONS: EmbeddedMigration[] = [
  {
    "tag": "0000_thin_jackal",
    "statements": [
      "CREATE TYPE \"public\".\"account_type\" AS ENUM('crypto', 'personal_cash', 'company_cash', 'savings', 'brokerage');",
      "CREATE TYPE \"public\".\"asset_class\" AS ENUM('ro_stock', 'us_stock', 'crypto', 'reit', 'mutual_fund', 'gold', 'other');",
      "CREATE TYPE \"public\".\"cashflow_kind\" AS ENUM('income', 'expense');",
      "CREATE TYPE \"public\".\"compounding\" AS ENUM('simple', 'monthly', 'annual');",
      "CREATE TYPE \"public\".\"direction\" AS ENUM('buy', 'sell');",
      "CREATE TYPE \"public\".\"loan_backed\" AS ENUM('property', 'business', 'personal', 'none');",
      "CREATE TYPE \"public\".\"loan_status\" AS ENUM('active', 'repaid', 'defaulted');",
      "CREATE TABLE \"accounts\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"type\" \"account_type\" NOT NULL,\n\t\"balance\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"currency\" text DEFAULT 'EUR' NOT NULL,\n\t\"is_company\" boolean DEFAULT false NOT NULL,\n\t\"notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"cashflow_expense\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"month\" integer NOT NULL,\n\t\"year\" integer DEFAULT 2026 NOT NULL,\n\t\"label\" text NOT NULL,\n\t\"amount\" numeric(20, 6) NOT NULL,\n\t\"currency\" text DEFAULT 'GBP' NOT NULL,\n\t\"amount_eur\" numeric(20, 6) NOT NULL,\n\t\"category\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"cashflow_income\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"month\" integer NOT NULL,\n\t\"year\" integer DEFAULT 2026 NOT NULL,\n\t\"label\" text NOT NULL,\n\t\"amount\" numeric(20, 6) NOT NULL,\n\t\"currency\" text DEFAULT 'GBP' NOT NULL,\n\t\"amount_eur\" numeric(20, 6) NOT NULL,\n\t\"category\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"fx_rates\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"base\" text NOT NULL,\n\t\"quote\" text NOT NULL,\n\t\"rate\" numeric(18, 8) NOT NULL,\n\t\"fetched_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE \"loan_payments\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"loan_id\" integer NOT NULL,\n\t\"due_date\" date NOT NULL,\n\t\"amount\" numeric(20, 6) NOT NULL,\n\t\"currency\" text DEFAULT 'EUR' NOT NULL,\n\t\"paid\" boolean DEFAULT false NOT NULL,\n\t\"paid_date\" date,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"loans\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"borrower\" text NOT NULL,\n\t\"principal\" numeric(20, 6) NOT NULL,\n\t\"currency\" text DEFAULT 'EUR' NOT NULL,\n\t\"backed\" \"loan_backed\" DEFAULT 'none' NOT NULL,\n\t\"start_date\" date,\n\t\"interest_rate\" numeric(8, 4) DEFAULT '0' NOT NULL,\n\t\"compounding\" \"compounding\" DEFAULT 'simple' NOT NULL,\n\t\"term_months\" integer,\n\t\"status\" \"loan_status\" DEFAULT 'active' NOT NULL,\n\t\"notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"properties\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"value\" numeric(20, 6) NOT NULL,\n\t\"currency\" text DEFAULT 'EUR' NOT NULL,\n\t\"monthly_rent\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"is_rented\" boolean DEFAULT false NOT NULL,\n\t\"notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"property_income\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"property_id\" integer NOT NULL,\n\t\"year\" integer NOT NULL,\n\t\"income\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"roi\" numeric(10, 6) DEFAULT '0' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"realized_trades\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"asset_class\" \"asset_class\" NOT NULL,\n\t\"symbol\" text NOT NULL,\n\t\"open_date\" date,\n\t\"close_date\" date,\n\t\"quantity\" numeric(30, 12) DEFAULT '0' NOT NULL,\n\t\"cost\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"proceeds\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"pl\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"currency\" text DEFAULT 'USD' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"transactions\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"trade_date\" date NOT NULL,\n\t\"direction\" \"direction\" DEFAULT 'buy' NOT NULL,\n\t\"asset_class\" \"asset_class\" NOT NULL,\n\t\"symbol\" text NOT NULL,\n\t\"quantity\" numeric(30, 12) NOT NULL,\n\t\"unit_cost\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"cost_currency\" text DEFAULT 'USD' NOT NULL,\n\t\"current_price\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"price_currency\" text DEFAULT 'USD' NOT NULL,\n\t\"maturity_date\" date,\n\t\"notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "ALTER TABLE \"loan_payments\" ADD CONSTRAINT \"loan_payments_loan_id_loans_id_fk\" FOREIGN KEY (\"loan_id\") REFERENCES \"public\".\"loans\"(\"id\") ON DELETE no action ON UPDATE no action;",
      "ALTER TABLE \"property_income\" ADD CONSTRAINT \"property_income_property_id_properties_id_fk\" FOREIGN KEY (\"property_id\") REFERENCES \"public\".\"properties\"(\"id\") ON DELETE no action ON UPDATE no action;"
    ]
  },
  {
    "tag": "0001_property_rent_and_live",
    "statements": [
      "CREATE TYPE \"public\".\"property_status\" AS ENUM('active', 'sold');",
      "CREATE TABLE \"property_rent\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"property_id\" integer NOT NULL,\n\t\"year\" integer NOT NULL,\n\t\"month\" integer,\n\t\"amount\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"currency\" text DEFAULT 'EUR' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "ALTER TABLE \"properties\" ADD COLUMN \"status\" \"property_status\" DEFAULT 'active' NOT NULL;",
      "ALTER TABLE \"properties\" ADD COLUMN \"purchase_date\" date;",
      "ALTER TABLE \"properties\" ADD COLUMN \"purchase_price\" numeric(20, 6);",
      "ALTER TABLE \"properties\" ADD COLUMN \"sale_date\" date;",
      "ALTER TABLE \"properties\" ADD COLUMN \"sale_price\" numeric(20, 6);",
      "ALTER TABLE \"property_rent\" ADD CONSTRAINT \"property_rent_property_id_properties_id_fk\" FOREIGN KEY (\"property_id\") REFERENCES \"public\".\"properties\"(\"id\") ON DELETE no action ON UPDATE no action;"
    ]
  },
  {
    "tag": "0002_wedding_legend",
    "statements": [
      "CREATE TABLE \"income_legend\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"label\" text NOT NULL,\n\t\"category\" text DEFAULT 'other' NOT NULL,\n\t\"custom_label\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"wedding_items\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"label\" text NOT NULL,\n\t\"paid\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"remaining\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"currency\" text DEFAULT 'RON' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);"
    ]
  },
  {
    "tag": "0003_property_ledger",
    "statements": [
      "CREATE TYPE \"public\".\"property_ledger_kind\" AS ENUM('acquisition', 'sale');",
      "CREATE TABLE \"property_ledger\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"property_id\" integer NOT NULL,\n\t\"kind\" \"property_ledger_kind\" NOT NULL,\n\t\"label\" text NOT NULL,\n\t\"amount\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"currency\" text DEFAULT 'EUR' NOT NULL,\n\t\"occurred_on\" date,\n\t\"notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "ALTER TABLE \"property_ledger\" ADD CONSTRAINT \"property_ledger_property_id_properties_id_fk\" FOREIGN KEY (\"property_id\") REFERENCES \"public\".\"properties\"(\"id\") ON DELETE no action ON UPDATE no action;"
    ]
  },
  {
    "tag": "0004_loan_receipts",
    "statements": [
      "CREATE TYPE \"public\".\"receipt_kind\" AS ENUM('principal', 'interest');",
      "CREATE TYPE \"public\".\"receipt_method\" AS ENUM('cash', 'bank_transfer');",
      "CREATE TABLE \"loan_receipts\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"loan_id\" integer NOT NULL,\n\t\"kind\" \"receipt_kind\" DEFAULT 'principal' NOT NULL,\n\t\"amount\" numeric(20, 6) NOT NULL,\n\t\"currency\" text DEFAULT 'EUR' NOT NULL,\n\t\"received_on\" date NOT NULL,\n\t\"method\" \"receipt_method\" DEFAULT 'bank_transfer' NOT NULL,\n\t\"bank\" text,\n\t\"notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "ALTER TABLE \"loan_receipts\" ADD CONSTRAINT \"loan_receipts_loan_id_loans_id_fk\" FOREIGN KEY (\"loan_id\") REFERENCES \"public\".\"loans\"(\"id\") ON DELETE no action ON UPDATE no action;"
    ]
  },
  {
    "tag": "0005_wedding_gifts",
    "statements": [
      "CREATE TABLE \"wedding_gifts\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"type\" text DEFAULT 'Nuntă' NOT NULL,\n\t\"amount\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"currency\" text DEFAULT 'RON' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);"
    ]
  },
  {
    "tag": "0006_watchlist_alerts",
    "statements": [
      "CREATE TYPE \"public\".\"alert_direction\" AS ENUM('above', 'below');",
      "CREATE TABLE \"price_alerts\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"symbol\" text NOT NULL,\n\t\"asset_class\" \"asset_class\" NOT NULL,\n\t\"target_price\" numeric(20, 6) NOT NULL,\n\t\"currency\" text DEFAULT 'USD' NOT NULL,\n\t\"direction\" \"alert_direction\" NOT NULL,\n\t\"active\" boolean DEFAULT true NOT NULL,\n\t\"triggered_at\" timestamp with time zone,\n\t\"triggered_price\" numeric(20, 6),\n\t\"acknowledged_at\" timestamp with time zone,\n\t\"note\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"watchlist\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"symbol\" text NOT NULL,\n\t\"asset_class\" \"asset_class\" NOT NULL,\n\t\"label\" text,\n\t\"sort_order\" integer DEFAULT 0 NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);"
    ]
  },
  {
    "tag": "0007_bent_the_anarchist",
    "statements": [
      "CREATE TABLE \"net_worth_snapshots\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"snapshot_date\" date NOT NULL,\n\t\"total_eur\" numeric(20, 6) NOT NULL,\n\t\"personal_eur\" numeric(20, 6) NOT NULL,\n\t\"investments_eur\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"accounts_eur\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"loans_eur\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"properties_eur\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone,\n\tCONSTRAINT \"net_worth_snapshots_snapshot_date_unique\" UNIQUE(\"snapshot_date\")\n);"
    ]
  },
  {
    "tag": "0008_spooky_silverclaw",
    "statements": [
      "CREATE TABLE \"dividends\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"symbol\" text NOT NULL,\n\t\"asset_class\" \"asset_class\" DEFAULT 'ro_stock' NOT NULL,\n\t\"ex_date\" date,\n\t\"pay_date\" date NOT NULL,\n\t\"amount_per_share\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"currency\" text DEFAULT 'RON' NOT NULL,\n\t\"note\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);"
    ]
  },
  {
    "tag": "0009_dividend_net_amount",
    "statements": [
      "ALTER TABLE \"dividends\" ADD COLUMN \"net_amount\" numeric(20, 6);"
    ]
  },
  {
    "tag": "0010_commission_sale_tax",
    "statements": [
      "ALTER TABLE \"transactions\" ADD COLUMN \"commission\" numeric(20, 6);",
      "ALTER TABLE \"transactions\" ADD COLUMN \"sale_tax\" numeric(20, 6);"
    ]
  },
  {
    "tag": "0011_share_links",
    "statements": [
      "CREATE TABLE \"share_links\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"token_hash\" text NOT NULL,\n\t\"label\" text DEFAULT '' NOT NULL,\n\t\"allowed_tabs\" text[] DEFAULT '{}' NOT NULL,\n\t\"expires_at\" timestamp with time zone,\n\t\"revoked_at\" timestamp with time zone,\n\t\"last_viewed_at\" timestamp with time zone,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone,\n\tCONSTRAINT \"share_links_token_hash_unique\" UNIQUE(\"token_hash\")\n);"
    ]
  },
  {
    "tag": "0012_businesses_clients",
    "statements": [
      "CREATE TYPE \"public\".\"business_status\" AS ENUM('active', 'sold', 'closed');",
      "CREATE TYPE \"public\".\"business_ledger_kind\" AS ENUM('revenue', 'cogs', 'ad_spend', 'expense');",
      "CREATE TYPE \"public\".\"client_status\" AS ENUM('active', 'paused', 'churned');",
      "CREATE TYPE \"public\".\"service_type\" AS ENUM('monthly_retainer', 'one_off', 'annual_hosting', 'marketing', 'reporting', 'hourly', 'other');",
      "CREATE TYPE \"public\".\"service_cadence\" AS ENUM('monthly', 'quarterly', 'annual', 'one_off', 'times_per_year');",
      "CREATE TABLE \"businesses\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"currency\" text DEFAULT 'EUR' NOT NULL,\n\t\"status\" \"business_status\" DEFAULT 'active' NOT NULL,\n\t\"valuation\" numeric(20, 6),\n\t\"started_on\" date,\n\t\"notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"business_ledger\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"business_id\" integer NOT NULL,\n\t\"year\" integer NOT NULL,\n\t\"month\" integer,\n\t\"kind\" \"business_ledger_kind\" DEFAULT 'revenue' NOT NULL,\n\t\"amount\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"currency\" text DEFAULT 'EUR' NOT NULL,\n\t\"label\" text,\n\t\"notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"clients\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"name\" text NOT NULL,\n\t\"status\" \"client_status\" DEFAULT 'active' NOT NULL,\n\t\"currency\" text DEFAULT 'EUR' NOT NULL,\n\t\"notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE \"client_services\" (\n\t\"id\" serial PRIMARY KEY NOT NULL,\n\t\"client_id\" integer NOT NULL,\n\t\"type\" \"service_type\" DEFAULT 'monthly_retainer' NOT NULL,\n\t\"label\" text,\n\t\"amount\" numeric(20, 6) DEFAULT '0' NOT NULL,\n\t\"currency\" text DEFAULT 'EUR' NOT NULL,\n\t\"cadence\" \"service_cadence\" DEFAULT 'monthly' NOT NULL,\n\t\"times_per_year\" integer,\n\t\"hours\" numeric(12, 2),\n\t\"rate\" numeric(20, 6),\n\t\"start_date\" date,\n\t\"renewal_date\" date,\n\t\"active\" boolean DEFAULT true NOT NULL,\n\t\"notes\" text,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "ALTER TABLE \"net_worth_snapshots\" ADD COLUMN \"businesses_eur\" numeric(20, 6) DEFAULT '0' NOT NULL;",
      "ALTER TABLE \"business_ledger\" ADD CONSTRAINT \"business_ledger_business_id_businesses_id_fk\" FOREIGN KEY (\"business_id\") REFERENCES \"public\".\"businesses\"(\"id\") ON DELETE no action ON UPDATE no action;",
      "ALTER TABLE \"client_services\" ADD CONSTRAINT \"client_services_client_id_clients_id_fk\" FOREIGN KEY (\"client_id\") REFERENCES \"public\".\"clients\"(\"id\") ON DELETE no action ON UPDATE no action;"
    ]
  },
  {
    "tag": "0013_service_cadence_weekly",
    "statements": [
      "ALTER TYPE \"public\".\"service_cadence\" ADD VALUE IF NOT EXISTS 'weekly' BEFORE 'monthly';"
    ]
  },
  {
    "tag": "0014_service_cadence_four_monthly",
    "statements": [
      "ALTER TYPE \"public\".\"service_cadence\" ADD VALUE IF NOT EXISTS 'four_monthly' AFTER 'quarterly';"
    ]
  },
  {
    "tag": "9999_packaging_tables",
    "statements": [
      "CREATE TABLE IF NOT EXISTS \"app_config\" (\n\t\"id\" integer PRIMARY KEY DEFAULT 1 NOT NULL,\n\t\"setup_completed_at\" timestamp with time zone,\n\t\"schema_version\" text NOT NULL,\n\t\"display_currency\" text DEFAULT 'EUR' NOT NULL,\n\t\"share_activation\" boolean DEFAULT false NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"updated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"deleted_at\" timestamp with time zone\n);",
      "CREATE TABLE IF NOT EXISTS \"owner\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"email\" text,\n\t\"password_hash\" text NOT NULL,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);",
      "CREATE TABLE IF NOT EXISTS \"license\" (\n\t\"id\" integer PRIMARY KEY DEFAULT 1 NOT NULL,\n\t\"key\" text NOT NULL,\n\t\"activated_at\" timestamp with time zone DEFAULT now() NOT NULL,\n\t\"tier\" text DEFAULT 'self-host' NOT NULL,\n\t\"updates_until\" timestamp with time zone\n);",
      "CREATE TABLE IF NOT EXISTS \"import_jobs\" (\n\t\"id\" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,\n\t\"asset_class\" text NOT NULL,\n\t\"status\" text DEFAULT 'pending' NOT NULL,\n\t\"row_count\" integer,\n\t\"created_at\" timestamp with time zone DEFAULT now() NOT NULL\n);"
    ]
  },
  {
    "tag": "9999b_share_activation",
    "statements": [
      "ALTER TABLE \"app_config\" ADD COLUMN IF NOT EXISTS \"share_activation\" boolean DEFAULT false NOT NULL;"
    ]
  }
];
